apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    {{ .Values.domain }} {
      encode gzip
      # API service only
      reverse_proxy {{ .Values.apiService }}.{{ .Values.apiNamespace }}.svc.cluster.local:{{ .Values.apiPort }}
    }
