name: Build and Push API Image

on:
  push:
    branches: ["main"]
    paths:
      - "api/**"
      - "helm/**"
      - ".github/workflows/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            malshinim/luzapi:latest
            malshinim/luzapi:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


