name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres_test
      NODE_ENV: test
      CI: true

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
          run_install: false

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Configure pnpm registry
        run: pnpm config set registry https://registry.npmjs.org

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install all workspace dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup test database
        run: node api/scripts/setup-test-db.js

      - name: Run linting (workspace filtered)
        run: pnpm exec eslint api/src --ext .ts --fix

      - name: Run type checking (workspace filtered)
        run: pnpm --filter api typecheck

      - name: Run tests with coverage (workspace filtered)
        run: pnpm --filter api test:coverage

      - name: Enforce coverage thresholds
        if: always()
        run: node api/scripts/enforce-coverage.js

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: api/coverage/
          retention-days: 7

      - name: Coverage summary
        if: always()
        run: node api/scripts/ci-coverage-summary.js

      - name: Comment coverage on PR
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: api/coverage/coverage-summary.md
